pipeline {
  agent any

  tools {
    nodejs "node"
    docker "docker"
  }

  stages {

    stage('Install dependencies') {
      steps {
        sh 'npm install -g yarn'
        sh 'yarn install'
      }
    }

  }
}