pipeline {
  agent any

  tools {nodejs "node"}

  stages {
    stage('Evaluate Stage') {
      steps {
        sh 'ls'
      }
    }

    stage('Cloning Git') {
      steps {
        git 'https://github.com/bryanculver/sample-node-ts.git'
      }
    }

    stage('Install dependencies') {
      steps {
        sh 'npm install -g yarn'
        sh 'yarn install'
      }
    }

  }
}